[package]
name = "netconf-client"
version = "0.1.0"
authors = ["rsitko92 <robert.sitko92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.9.5"
serde = { version = "1.0.226", features = ["derive"] }
quick-xml = { version = "0.38.3", features = ["serialize"] }
thiserror = "2.0.16"
regex = "1.5.4"
strum = "0.27.2"
strum_macros = "0.27.2"
heck = "0.5.0"

[dev-dependencies]
serial_test = "3.2.0"
bollard = "0.11.1"
tokio = { version = "1.47.1", features = ["rt", "macros"] }
futures-util = "0.3.31"
confy = "0.4.0"
lazy_static = "1.5.0"
